service: th-frontend
frameworkVersion: '3'

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2

plugins:
  # - serverless-domain-manager
  # - serverless-certificate-creator
  - serverless-lift

constructs:
  crowdyChat:
    type: single-page-app
    path: build
    domain:
      - app.crowdy.chat
    # certificate: arn:aws:acm:us-east-1:730335628944:certificate/579b6563-5ff5-4a43-8094-a65a190a0cc2


custom:
  customCertificate:
    certificateName: 'app.crowdy.chat'
    # idempotencyToken: 'abcsomedomainio' //optional
    # hostedZoneNames: 'trendshub.co.in'
    hostedZoneIds: Z08929472ONQ8YE8XDCVA
    # region: eu-west-1 // optional - default is us-east-1 which is required for custom api gateway domains of Type Edge (default)
    enabled: true
    rewriteRecords: false
  customDomain:
    domainName: app.crowdy.chat
    basePath: ''
    stage: dev
    certificateName: 'app.crowdy.chat'
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2



resources:
  Resources:
    Route53Record:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: Z08929472ONQ8YE8XDCVA # Your HostedZoneId
        Name: app.crowdy.chat
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # Cloudfront Route53 HostedZoneId. This does not change.
          DNSName: ${construct:crowdyChat.cname}

